[build]
  publish = "public"
  command = ""

[context.deploy-preview]
  command = ""
  
[context.branch-deploy]
  command = ""

# Automatic deploy previews for all branches and PRs
[build.processing]
  skip_processing = false

# SPA redirect for single page applications
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
